app.name=OJ AI Tester
app.tempDir=temp

db.url=jdbc:sqlserver://localhost:1433;databaseName=OJ_AI_TESTER;encrypt=true;trustServerCertificate=true;integratedSecurity=true

ai.provider=gemini
ai.apiKey=AIzaSyBragMtKXcy67mcbRNCWqKd8SAZjElV9HM
ai.model=gemini-2.5-flash

execution.timeLimitMs=2000
execution.memoryLimitMb=256

ocr.tesseractPath=C:/Program Files/Tesseract-OCR/tesseract.exe
ocr.language=eng